import { Inter } from "next/font/google";
import Head from "next/head";
import React from "react";
import "./globals.css";
import 'devicon/devicon.min.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hamza's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="shortcut icon" href={require('../../public/favicon.ico')} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
